### ISSUE TITLE
Add timecontrols (pause, speed 1, 2, 3)

### ISSUE THREAD

**Issue by ViddeM** [Tevej/DayInGothenburgInTime#64]
- [ ] Fix deltaTime (make dynamic).
- [ ] Add possibility to manipulate deltaTime with hotkeys (ex: space, numbers 1, 2, 3).

**Comment by jerge** [comment]
[] create time variable in "Game"
- [] use time variable in "Game"
[] create system for manipulation of time variable
[] bind Signal for system to hotkey
